FROM amazon/aws-cli

ENV AWS_ACCESS_KEY_ID=fake_access_key\
    AWS_SECRET_ACCESS_KEY=fake_secret_access_key\
    DYNAMODB_REGION=ap-northeast-1

COPY ./ddl /usr/app/ddl

RUN chmod +x /usr/app/ddl/createTable.sh

WORKDIR /usr/app/ddl