/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-1',
  aws_dynamodb_all_tables_region: 'ap-northeast-1',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'todos-dev',
      region: 'ap-northeast-1',
    },
  ],
  aws_cognito_identity_pool_id:
    'ap-northeast-1:2dde0e1b-7b37-489f-ac20-71ec83695959',
  aws_cognito_region: 'ap-northeast-1',
  aws_user_pools_id: 'ap-northeast-1_0dNK06LSN',
  aws_user_pools_web_client_id: '160d6emtjm0aq375frt20td5pv',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_cloud_logic_custom: [
    {
      name: 'mytodoapi',
      endpoint:
        'https://k22r7se45b.execute-api.ap-northeast-1.amazonaws.com/dev',
      region: 'ap-northeast-1',
    },
  ],
}

export default awsmobile
